### ISSUE TITLE
quadratic equation

### ISSUE THREAD

**Issue by awaissaddiqui** [random957654/Hactober-2023-1#541]
Calculating the roots of a quadratic equation is something that we have learnt in childhood. However, the complexity of quadratic equations increased with time. The methods to deal with this problem have also evolved. In this article, we would take a look a way to write a C program to find the roots of a quadratic equation.

**Comment by Tejsvapandey1** [comment]
@MSubhajitIND sir please assign this Problem to me

**Comment by steeltitancoder2210** [comment]
@MSubhajitIND sir pls assign it to me

**Comment by steeltitancoder2210** [comment]
A quadratic equation is a second-degree polynomial equation that can be written in the standard form:

ax^2 + bx + c = 0

In this equation:
- "x" is the variable representing the unknown value you're trying to solve for.
- "a," "b," and "c" are constants, with "a" not equal to zero. These constants determine the shape and characteristics of the quadratic equation.

The solutions to a quadratic equation are found by using the quadratic formula:

x = (-b ± √(b² - 4ac)) / (2a)

The quadratic formula gives the values of "x" that make the equation equal to zero. There are typically two solutions, which are often referred to as "roots."

Key concepts related to quadratic equations include:

1. Discriminant (D): The value inside the square root in the quadratic formula, i.e., D = b² - 4ac. The discriminant determines the nature of the roots:
   - If D > 0, there are two distinct real roots.
   - If D = 0, there is one real root (a repeated root).
   - If D < 0, there are no real roots (complex roots).

2. Vertex: The vertex of a quadratic equation in the form y = ax^2 + bx + c is given by the coordinates (-b/2a, f(-b/2a)), where f(x) is the value of the quadratic equation.

3. Axis of Symmetry: The line x = -b/2a, which passes through the vertex, is the axis of symmetry. The quadratic graph is symmetric with respect to this line.

4. Parabola: The graph of a quadratic equation is a parabola. Its direction (upward or downward) depends on the sign of "a."

5. Quadratic Functions: Quadratic equations are often used to model various real-world phenomena. They are a type of quadratic function, where "a," "b," and "c" represent parameters that influence the shape and position of the parabola.

6. Solving Quadratic Equations: To solve a quadratic equation, you can use the quadratic formula, factoring, completing the square, or graphing. The method you choose depends on the equation and your preference.

Applications of quadratic equations are widespread, including in physics, engineering, economics, and many other fields. They are particularly useful in problems involving motion, optimization, and modeling various physical phenomena.

It's important to understand quadratic equations because they are fundamental to algebra and mathematics. They are a stepping stone to more advanced topics and are applicable in a wide range of practical situations.

**Comment by steeltitancoder2210** [comment]
how to fire pr against this

**Comment by vamus092** [comment]
Assign me the issue

**Comment by zykuriku** [comment]
can i work on this?

**Comment by simranroy01** [comment]
please assign this to me
